// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QLSV_API.Repository;

#nullable disable

namespace QLSV_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250515120508_Update_ModelNhanVien")]
    partial class Update_ModelNhanVien
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QLSV_API.Model.DoanChat", b =>
                {
                    b.Property<string>("Ma_DC")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaNguoiGui")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaNguoiNhan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ma_YC")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Ma_DC");

                    b.HasIndex("Ma_YC");

                    b.ToTable("DoanChats");
                });

            modelBuilder.Entity("QLSV_API.Model.LichSuYeuCau", b =>
                {
                    b.Property<string>("Ma_LSYC")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Ma_YC")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TrangThaiCu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThaiMoi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Ma_LSYC");

                    b.HasIndex("Ma_YC");

                    b.ToTable("LichSuYeuCaus");
                });

            modelBuilder.Entity("QLSV_API.Model.LoaiTaiKhoan", b =>
                {
                    b.Property<string>("Ma_Loai")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Ten_Loai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Ma_Loai");

                    b.ToTable("LoaiTaiKhoans");

                    b.HasData(
                        new
                        {
                            Ma_Loai = "ADMIN",
                            Ten_Loai = "Administrator"
                        },
                        new
                        {
                            Ma_Loai = "NEWS",
                            Ten_Loai = "News Publisher"
                        },
                        new
                        {
                            Ma_Loai = "REQUEST",
                            Ten_Loai = "Request Handler"
                        },
                        new
                        {
                            Ma_Loai = "STUDENT",
                            Ten_Loai = "Student Manager"
                        });
                });

            modelBuilder.Entity("QLSV_API.Model.LoaiYeuCau", b =>
                {
                    b.Property<string>("Ma_loaiYC")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Ten_loaiYC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Ma_loaiYC");

                    b.ToTable("LoaiYeuCaus");
                });

            modelBuilder.Entity("QLSV_API.Model.Lop", b =>
                {
                    b.Property<string>("MaLop")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenLop")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaLop");

                    b.ToTable("Lops");
                });

            modelBuilder.Entity("QLSV_API.Model.NhanVien", b =>
                {
                    b.Property<string>("Ma_NV")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ChucVu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gioitinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NamVaoLam")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten_NV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Ma_NV");

                    b.ToTable("NhanViens");

                    b.HasData(
                        new
                        {
                            Ma_NV = "NV0001",
                            ChucVu = "Admin",
                            DiaChi = "Bạc Liêu",
                            Email = "htuan15424@gmail.com",
                            Gioitinh = "Nam",
                            NamVaoLam = 2015,
                            NgaySinh = new DateTime(2004, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SDT = "0987654321",
                            Ten_NV = "Lê Đăng Hoàng Tuấn"
                        });
                });

            modelBuilder.Entity("QLSV_API.Model.SinhVien", b =>
                {
                    b.Property<string>("Ma_SV")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BacDaoTao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gioi_Tinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KhoaHoc")
                        .HasColumnType("int");

                    b.Property<string>("LoaiHinhDaoTao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LopHoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaLop")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nganh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ten_SV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Ma_SV");

                    b.HasIndex("MaLop");

                    b.ToTable("SinhViens");
                });

            modelBuilder.Entity("QLSV_API.Model.TaiKhoan", b =>
                {
                    b.Property<string>("Ma_TK")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Ma_Loai")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Ma_NV")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Ma_TK");

                    b.HasIndex("Ma_Loai");

                    b.HasIndex("Ma_NV");

                    b.ToTable("TaiKhoans");

                    b.HasData(
                        new
                        {
                            Ma_TK = "A0001",
                            Ma_Loai = "Admin",
                            Ma_NV = "NV0001",
                            MatKhau = "123456789",
                            TenDangNhap = "admin1"
                        });
                });

            modelBuilder.Entity("QLSV_API.Model.TaiKhoanSinhVien", b =>
                {
                    b.Property<string>("Ma_TKSV")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Ma_SV")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Ma_TKSV");

                    b.HasIndex("Ma_SV");

                    b.ToTable("TaiKhoanSinhViens");
                });

            modelBuilder.Entity("QLSV_API.Model.ThongBao", b =>
                {
                    b.Property<string>("Ma_TT")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnOrder(0);

                    b.Property<string>("Ma_TKSV")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.HasKey("Ma_TT", "Ma_TKSV");

                    b.HasIndex("Ma_TKSV");

                    b.ToTable("ThongBaos");
                });

            modelBuilder.Entity("QLSV_API.Model.ThongBaoYeuCau", b =>
                {
                    b.Property<string>("Ma_TBYC")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Ma_TKSV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ma_YC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayThongBao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaiKhoanSinhVienMa_TKSV")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("YeuCauMa_YC")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Ma_TBYC");

                    b.HasIndex("TaiKhoanSinhVienMa_TKSV");

                    b.HasIndex("YeuCauMa_YC");

                    b.ToTable("ThongBaoYeuCaus");
                });

            modelBuilder.Entity("QLSV_API.Model.TinTuc", b =>
                {
                    b.Property<string>("Ma_TT")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Ma_TK")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Ma_TT");

                    b.HasIndex("Ma_TK");

                    b.ToTable("TinTucs");
                });

            modelBuilder.Entity("QLSV_API.Model.XuLyYeuCau", b =>
                {
                    b.Property<string>("Ma_YC")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnOrder(0);

                    b.Property<string>("Ma_TK")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("NgayXuLy")
                        .HasColumnType("datetime2");

                    b.HasKey("Ma_YC", "Ma_TK");

                    b.HasIndex("Ma_TK");

                    b.ToTable("XuLyYeuCaus");
                });

            modelBuilder.Entity("QLSV_API.Model.YeuCau", b =>
                {
                    b.Property<string>("Ma_YC")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Ma_TKSV")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Ma_loaiYC")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Ma_YC");

                    b.HasIndex("Ma_TKSV");

                    b.HasIndex("Ma_loaiYC");

                    b.ToTable("YeuCaus");
                });

            modelBuilder.Entity("QLSV_API.Model.DoanChat", b =>
                {
                    b.HasOne("QLSV_API.Model.YeuCau", "YeuCau")
                        .WithMany()
                        .HasForeignKey("Ma_YC")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("YeuCau");
                });

            modelBuilder.Entity("QLSV_API.Model.LichSuYeuCau", b =>
                {
                    b.HasOne("QLSV_API.Model.YeuCau", "YeuCau")
                        .WithMany()
                        .HasForeignKey("Ma_YC")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("YeuCau");
                });

            modelBuilder.Entity("QLSV_API.Model.SinhVien", b =>
                {
                    b.HasOne("QLSV_API.Model.Lop", "Lop")
                        .WithMany("SinhViens")
                        .HasForeignKey("MaLop")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lop");
                });

            modelBuilder.Entity("QLSV_API.Model.TaiKhoan", b =>
                {
                    b.HasOne("QLSV_API.Model.LoaiTaiKhoan", "LoaiTaiKhoan")
                        .WithMany("TaiKhoans")
                        .HasForeignKey("Ma_Loai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLSV_API.Model.NhanVien", "NhanVien")
                        .WithMany("TaiKhoans")
                        .HasForeignKey("Ma_NV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiTaiKhoan");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QLSV_API.Model.TaiKhoanSinhVien", b =>
                {
                    b.HasOne("QLSV_API.Model.SinhVien", "SinhVien")
                        .WithMany("TaiKhoanSinhViens")
                        .HasForeignKey("Ma_SV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("QLSV_API.Model.ThongBao", b =>
                {
                    b.HasOne("QLSV_API.Model.TaiKhoanSinhVien", "TaiKhoanSinhVien")
                        .WithMany()
                        .HasForeignKey("Ma_TKSV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLSV_API.Model.TinTuc", "TinTuc")
                        .WithMany()
                        .HasForeignKey("Ma_TT")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoanSinhVien");

                    b.Navigation("TinTuc");
                });

            modelBuilder.Entity("QLSV_API.Model.ThongBaoYeuCau", b =>
                {
                    b.HasOne("QLSV_API.Model.TaiKhoanSinhVien", "TaiKhoanSinhVien")
                        .WithMany()
                        .HasForeignKey("TaiKhoanSinhVienMa_TKSV");

                    b.HasOne("QLSV_API.Model.YeuCau", "YeuCau")
                        .WithMany()
                        .HasForeignKey("YeuCauMa_YC")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoanSinhVien");

                    b.Navigation("YeuCau");
                });

            modelBuilder.Entity("QLSV_API.Model.TinTuc", b =>
                {
                    b.HasOne("QLSV_API.Model.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("Ma_TK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("QLSV_API.Model.XuLyYeuCau", b =>
                {
                    b.HasOne("QLSV_API.Model.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("Ma_TK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLSV_API.Model.YeuCau", "YeuCau")
                        .WithMany("XuLyYeuCaus")
                        .HasForeignKey("Ma_YC")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");

                    b.Navigation("YeuCau");
                });

            modelBuilder.Entity("QLSV_API.Model.YeuCau", b =>
                {
                    b.HasOne("QLSV_API.Model.TaiKhoanSinhVien", "TaiKhoanSinhVien")
                        .WithMany("YeuCaus")
                        .HasForeignKey("Ma_TKSV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLSV_API.Model.LoaiYeuCau", "LoaiYeuCau")
                        .WithMany("YeuCaus")
                        .HasForeignKey("Ma_loaiYC")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiYeuCau");

                    b.Navigation("TaiKhoanSinhVien");
                });

            modelBuilder.Entity("QLSV_API.Model.LoaiTaiKhoan", b =>
                {
                    b.Navigation("TaiKhoans");
                });

            modelBuilder.Entity("QLSV_API.Model.LoaiYeuCau", b =>
                {
                    b.Navigation("YeuCaus");
                });

            modelBuilder.Entity("QLSV_API.Model.Lop", b =>
                {
                    b.Navigation("SinhViens");
                });

            modelBuilder.Entity("QLSV_API.Model.NhanVien", b =>
                {
                    b.Navigation("TaiKhoans");
                });

            modelBuilder.Entity("QLSV_API.Model.SinhVien", b =>
                {
                    b.Navigation("TaiKhoanSinhViens");
                });

            modelBuilder.Entity("QLSV_API.Model.TaiKhoanSinhVien", b =>
                {
                    b.Navigation("YeuCaus");
                });

            modelBuilder.Entity("QLSV_API.Model.YeuCau", b =>
                {
                    b.Navigation("XuLyYeuCaus");
                });
#pragma warning restore 612, 618
        }
    }
}
